name: CI Pipeline

on:
  push:
    branches:
      - main
      - feature/app-integration
  pull_request:
    branches:
      - main
      - feature/app-integration

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # Checkout репозитория
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: Testing

      # Установка Node.js с кэшированием
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            Testing/client/package-lock.json
            Testing/server/package-lock.json

      # Установка Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Установка зависимостей для client
      - name: Install Client Dependencies
        run: |
          cd Testing/client
          npm ci --prefer-offline --cache .npm
          ls -la
          cat package.json
          echo "Client dependencies installed"
        timeout-minutes: 5

      # Установка зависимостей для server
      - name: Install Server Dependencies
        run: |
          cd Testing/server
          npm ci --prefer-offline --cache .npm
          ls -la
          cat package.json
          echo "Server dependencies installed"
        timeout-minutes: 5

      # Сборка server
      - name: Build Server
        run: |
          cd Testing/server
          npx prisma generate
          npx tsc
          ls -la dist || echo "No dist directory found"
          echo "Server built"

      # Установка зависимостей для тестов
      - name: Install Test Dependencies
        run: |
          cd Testing
          pip install -r requirements.txt
          pip list
          pip show allure-pytest
          echo "Test dependencies installed"

      # Запуск сервера в фоновом режиме
      - name: Start Server
        run: |
          cd Testing/server
          npm run start &
          sleep 30
          netstat -tulnp | grep 3001 || echo "No process listening on port 3001"
          ps aux | grep node || echo "No node processes running"
          echo "Server started"
        env:
          PORT: 3001  # Устанавливаем порт для сервера

      # Запуск клиента в фоновом режиме
      - name: Start Client
        run: |
          cd Testing/client
          npm run dev &
          sleep 30
          netstat -tulnp | grep 3000 || echo "No process listening on port 3000"
          ps aux | grep node || echo "No node processes running"
          echo "Client started"

      # Проверка доступности приложения
      - name: Check Application Availability
        run: |
          curl --retry 5 --retry-delay 5 --retry-max-time 30 http://localhost:3000 || exit 1
          curl --retry 5 --retry-delay 5 --retry-max-time 30 http://localhost:3000/authentication || exit 1
          curl --retry 5 --retry-delay 5 --retry-max-time 30 http://localhost:3001/health || exit 1
          echo "Application is accessible"

      # Запуск тестов
      - name: Run Tests
        run: |
          cd Testing
          pytest --alluredir=allure-results
        env:
          BASE_URL: http://localhost:3000
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}

      # Генерация и загрузка отчета Allure
      - name: Generate Allure Report
        if: always()
        run: |
          cd Testing
          allure generate allure-results -o allure-report --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Загрузка отчета Allure
      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: Testing/allure-report