# .github/workflows/ci.yml
name: CI Pipeline
on:
  push:
    branches: [main, develop, feature/fix-tests]
  pull_request:
    branches: [main, develop]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install Playwright
        run: |
          pip install playwright
          playwright install
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Clone and start web app
        run: |
          git clone https://github.com/AhmedTrb/Project-Management-web-app.git
          cd Project-Management-web-app
          npm install
          npm start &
          sleep 20  # Ждём запуска сервера
      - name: Run tests with headless mode
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          BASE_URL: ${{ secrets.BASE_URL }}
          HEADLESS: true
        run: pytest --alluredir=allure-results
      - name: Generate Allure report
        if: always()
        run: |
          allure generate allure-results --clean -o allure-report
      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results
          path: allure-results/
      - name: Upload Allure report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report
          path: allure-report/
      - name: Check PEP 8
        run: flake8 .