name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create __init__.py in root
        run: touch __init__.py

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright
        run: |
          pip install playwright
          playwright install

      - name: Run tests
        run: |
          echo "Starting pytest..."
          pytest --alluredir=allure-results -v
          echo "Pytest completed."

      - name: Upload Allure results
        uses: actions/upload-artifact@v4.3.0
        if: always()
        with:
          name: allure-results
          path: allure-results/

      - name: Check PEP 8
        run: flake8 .